### PR TITLE
Handle IndexError in `WikipediaDescUtils` for wikitext

### LINKED ISSUE #101: Error `IndexError: list index out of range` while testing the entities extraction
Error raised

```
  File "experiments/jz/dataset/c4/python_scripts/add_metadata.py", line 165, in main
    raw_datasets = raw_datasets.map(
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/datasets/dataset_dict.py", line 482, in map
    {
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/datasets/dataset_dict.py", line 483, in <dictcomp>
    k: dataset.map(
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2018, in map
    return self._map_single(
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 521, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 488, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/datasets/fingerprint.py", line 411, in wrapper
    out = func(self, *args, **kwargs)
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2382, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2269, in apply_function_on_filtered_inputs
    function(*fn_args, effective_indices, **fn_kwargs) if with_indices else function(*fn_args, **fn_kwargs)
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1978, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/bsmetadata/preprocessing_utils.py", line 225, in preprocess
    ent_desc = self._extract_desc_from_entity(entity)
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/bsmetadata/preprocessing_utils.py", line 213, in _extract_desc_from_entity
    return self.entity_utils.fetch_entity_description_from_keyword(key)
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/bsmetadata/preprocessing_tools/wikipedia_desc_utils.py", line 50, in fetch_entity_description_from_keyword
    text = self.fetch_wikipedia_description_for_title(title)
  File "/gpfswork/rech/six/commun/conda/lucile-modelling-metadata/lib/python3.8/site-packages/bsmetadata/preprocessing_tools/wikipedia_desc_utils.py", line 26, in fetch_wikipedia_description_for_title
    text = self.wiki_dump_db.get_paragraphs(title)[0].text
IndexError: list index out of range
```

### PR DESCRIPTION
**Pull request by SaulLu**
Fix #101 

During my last test, I notice that the list of paragraphs can be empty (can you confirm that this could happen @manandey and @shanyas10 ?)

### CODE REVIEW

**Comment by shanyas10** [comment]
@SaulLu it could be that the key used for fetching paragraphs is not valid, which would result in key error (that we've already handled). Empty paragraphs are not something I've come across yet. Can you share a few cases where you're getting these?

**Comment by SaulLu** [comment]
@shanyas10, thank you for your answer! 

I encountered this problem on the 1000 examples toy dataset, especially during entities extraction. 

I put the stacktrace of the error obtained in the issue.

Currently, I don't have an easy way to know which examples caused this problem (I use `datasets.map` and jz). However, as it happened on the toy dataset, it should be possible to reproduce the error locally to identify the problematic example.

**Comment by manandey** [comment]
@SaulLu, I checked this and this did seem to happen in a few cases while fetching entity descriptions. Thanks for the fix!

**Review by manandey — APPROVED** [review]

**Review by shanyas10 — APPROVED** [review]
Thanks for the fix @SaulLu !

**Pull request merged**
