### PR TITLE
Replace dateutil submodule with renamed package

### LINKED ISSUE #63: Rename dateutil submodule with another name
There are reports that the current approach might not work with `pip install`.
So I am planning to drop the submodule, and rename the modified dateutil so we can add it to requirements.

cc. @SaulLu @shanyas10

### PR DESCRIPTION
**Pull request by cccntu**
Fix #63

Please try this and let me know if it works.

@chkla You can try to merge this to your PR branch.

### CODE REVIEW

**Comment by SaulLu** [comment]
Thank you so much for working on this change! I see that the test failed when installing the packages? I am afraid that the format in the `extras_require` of `setup.py` is not exactly as expected.

Maybe you could try the format I had shared to manandey  for the entity tags? [link](https://github.com/bigscience-workshop/metadata/pull/55#discussion_r753380056)

**Comment by cccntu** [comment]
@SaulLu  Thank you for the pointer! That saved me a lot of debugging.
The `#egg` suffix doesn't seem to be necessary so I dropped it. Is that ok? I don't really know what that means.
I also fixed a package related bug in `bs_dateutil` and bumped the version number.

**Comment by SaulLu** [comment]
You're welcome! Everything is going well with the installation now :confetti_ball: !

**Review by SaulLu — APPROVED** [review]
You're welcome! Everything is going well with the installation now confetti_ball !

**Pull request merged**
